export default {
    lang: "pt",
    pt: {
        "Dicom Server": "Dicom Servidor",
        "Sign in to Application": "Entrar no aplicativo",
        "User ID": "Usuário ID",
        "Enter user ID...": "Entrar usuário ID...",
        "Password": "Password",
        "Password Confirm": "Confirmação de Password",
        "Remember Password": "Lembrar Password",
        "Sign In": "Assinar",
        "Forgot Password": "Esquecida Password",
        "Register": "Registro",
        "All Rights Reserved by": "Todos os direitos reservados por",
        "Users": "Usuários",
        "SCP": "SCP",
        "S3 List": "S3 Lista",
        "PACs List": "PACs Lista",
        "Work Log": "Trabalho Tora",
        "Name": "Nome",
        "Email": "Email",
        "Status": "Status",
        "Actions": "Ações",
        "Active": "Activo",
        "Inactive": "Inativo",
        "Delete": "Deletar",
        "SCP Settings": "SCP Configurações",
        "Update": "Atualizar",
        "ID": "ID",
        "Title": "Título",
        "Modality Ignore": "Modalidade Ignorar",
        "Port": "Porta",
        "Sleep Time (minute)": "Tempo de sono (minuto)",
        "Temp save time (minute)": "Tempo de economia temporária (minuto)",
        "Update Success": "Atualização feita com sucesso",
        "Update Failed": "Atualização falhou",
        "AWS S3 Buckets setting": "Configuração de AWS S3 Buckets",
        "Add New": "Adicionar novo",
        "Bucket Name": "Nome do intervalo",
        "Private Key": "Chave privada",
        "Public Key": "Chave pública",
        "Console": "Console",
        "Cancel": "Cancelar",
        "Update Bucket": "Balde de atualização",
        "PACs Settings": "Configurações de PACs",
        "Host": "Hospedeiro",
        "Update PAC": "Atualizar PAC",
        "System Logs": "Logs do sistema",
        "Cloud_File_Path": "Caminho do Arquivo_Caminho",
        "Modality": "Modalidade",
        "PatientID": "PacienteID",
        "PatientName": "PacienteNome",
        "Patient Sex": "Paciente Sexo",
        "Patient Age": "Paciente Idade",
        "Patient Birthday": "Paciente Aniversário",
        "Exam.....": "Exame.....",
        "Accession_Number": "Acesso_Número",
        "Study Identification": "Identificação do Estudo",
        "Study Unified Identification": "Identificação Unificada de Estudo",
        "Referring Physician Name": "Nome do médico de referência",
        "Performing Physician Name": "Nome do médico assistente",
        "Study_Date": "Estudo_Data",
        "Record_Time": "Tempo recorde",
        "Origin ID": "Origem ID",
        "Origin Name": "Origem Nome",
        "Showing":"Mostrando",
        "to":"a",
        "of": "de",
        "Results": "Resultados",
        "Are you sure to delete?": "Você tem certeza que quer deletar?",
        "Add Failed": "Falha ao adicionar",
        "Update Failed": "Atualização falhou",
        "Invalid parameters": "Parâmetros inválidos",
        "Please select the UserID": "Selecione o ID do usuário",
        "Login failed": "Falha na autenticação",
        "Create Account": "Criar Conta",
        "We will never share your email with anyone else.": "Nós nunca iremos compartilhar seu e-mail com ninguém.",
        "Accept Terms and Privacy Policy": "Aceite os Termos e a Política de Privacidade", 
        "Email Address or Username": "Endereço de email ou nome de usuário",
        "Reset Password": "Redefinir Password",
        "Back to Home": "Voltar para casa",
        "Login": "Login",
        "Web Settings": "Web Configurações"
    }
}
